// Screen copy beyond Japanese and English. The key pairs the two source strings.
const uiCopy = <String, Map<String, String>>{
  '（未確認）|| (unverified)': {zh: '（未验证）', ko: ' (미확인)', es: ' (sin verificar)', fr: ' (non vérifié)'},
  '15文字以上。単語を並べた長めのフレーズがおすすめです。||15+ characters. A long phrase of words works well.': {zh: '至少15个字符。把几个词连成一句比较好记。', ko: '15자 이상. 단어를 이어 붙인 긴 문구를 권합니다.', es: '15 caracteres o más. Una frase larga de palabras funciona bien.', fr: '15 caractères ou plus. Une longue phrase de mots est plus sûre.'},
  '英数字と . _ - の3〜32文字||3–32 letters, digits, . _ -': {zh: '3–32个字母、数字和 . _ -', ko: '영문, 숫자, . _ - 로 3–32자', es: '3–32 letras, dígitos, . _ -', fr: '3–32 lettres, chiffres, . _ -'},
  '少し||A little': {zh: '一点', ko: '조금', es: 'Un poco', fr: 'Un peu'},
  'ガイド中の旅行があります||A trip is in progress': {zh: '有一段导览进行中', ko: '진행 중인 여행이 있습니다', es: 'Hay un viaje en curso', fr: 'Un voyage est en cours'},
  'ほかの国にいるときは、その国のマナーや習慣の話もします。||Abroad, the guide also tells you about local manners and customs.': {zh: '在其他国家时，也会讲当地的礼仪和习惯。', ko: '다른 나라에 있을 때는 그 나라의 예절과 습관도 들려줍니다.', es: 'En otro país, la guía también cuenta costumbres y modales locales.', fr: 'À l’étranger, le guide parle aussi des usages et des coutumes.'},
  'アカウント||Account': {zh: '账号', ko: '계정', es: 'Cuenta', fr: 'Compte'},
  '追加||Add': {zh: '添加', ko: '추가', es: 'Añadir', fr: 'Ajouter'},
  '言語を追加||Add a language': {zh: '添加语言', ko: '언어 추가', es: 'Añadir un idioma', fr: 'Ajouter une langue'},
  'ID・パスワードを追加||Add ID and password': {zh: '添加 ID 和密码', ko: 'ID와 비밀번호 추가', es: 'Añadir ID y contraseña', fr: 'Ajouter un identifiant et un mot de passe'},
  '前方||ahead': {zh: '前方', ko: '앞쪽', es: 'delante', fr: 'devant'},
  '旅行・位置・履歴・音声を含むすべてのデータを削除します。元に戻せません。||All trips, locations, history and audio will be deleted. This cannot be undone.': {zh: '将删除旅行、位置、历史和语音等全部数据。此操作无法撤销。', ko: '여행, 위치, 기록, 음성을 포함한 모든 데이터를 삭제합니다. 되돌릴 수 없습니다.', es: 'Se borrarán viajes, ubicaciones, historial y audio. No se puede deshacer.', fr: 'Tous les voyages, positions, historiques et audio seront supprimés. C’est irréversible.'},
  'すでに連携されています。||Already linked.': {zh: '已经关联。', ko: '이미 연동되어 있습니다.', es: 'Ya está vinculado.', fr: 'Déjà associé.'},
  '表示言語||App language': {zh: '显示语言', ko: '표시 언어', es: 'Idioma de la app', fr: 'Langue de l’app'},
  '建築||Architecture': {zh: '建筑', ko: '건축', es: 'Arquitectura', fr: 'Architecture'},
  'この辺り||around here': {zh: '这一带', ko: '이 근처', es: 'por aquí', fr: 'par ici'},
  '音声を用意できなかったため、文字で表示しています。||Audio is unavailable; showing text.': {zh: '无法准备语音，先显示文字。', ko: '음성을 준비하지 못해 글로 보여 줍니다.', es: 'El audio no está disponible; se muestra el texto.', fr: 'L’audio n’est pas prêt ; le texte s’affiche.'},
  'オーストラリア||Australia': {zh: '澳大利亚', ko: '호주', es: 'Australia', fr: 'Australie'},
  'オーストリア||Austria': {zh: '奥地利', ko: '오스트리아', es: 'Austria', fr: 'Autriche'},
  '自動||Auto': {zh: '自动', ko: '자동', es: 'Auto', fr: 'Auto'},
  '自動判定||Auto': {zh: '自动判断', ko: '자동 판별', es: 'Detección automática', fr: 'Détection auto'},
  '自動生成||Auto-generated': {zh: '自动生成', ko: '자동 생성', es: 'Generado automáticamente', fr: 'Généré automatiquement'},
  '後方||behind': {zh: '后方', ko: '뒤쪽', es: 'detrás', fr: 'derrière'},
  'ベルギー||Belgium': {zh: '比利时', ko: '벨기에', es: 'Bélgica', fr: 'Belgique'},
  '自転車||Bicycle': {zh: '自行车', ko: '자전거', es: 'Bicicleta', fr: 'Vélo'},
  'ブラジル||Brazil': {zh: '巴西', ko: '브라질', es: 'Brasil', fr: 'Brésil'},
  '出張||Business trip': {zh: '出差', ko: '출장', es: 'Viaje de trabajo', fr: 'Voyage d’affaires'},
  'カナダ||Canada': {zh: '加拿大', ko: '캐나다', es: 'Canadá', fr: 'Canada'},
  'キャンセル||Cancel': {zh: '取消', ko: '취소', es: 'Cancelar', fr: 'Annuler'},
  '通信できません。電波の良い場所で再度お試しください。||Cannot reach the server. Please try again.': {zh: '无法连接服务器。请在信号较好的地方再试。', ko: '서버에 연결할 수 없습니다. 신호가 좋은 곳에서 다시 시도해 주세요.', es: 'No se puede contactar con el servidor. Inténtelo de nuevo.', fr: 'Impossible de joindre le serveur. Réessayez.'},
  '車||Car': {zh: '汽车', ko: '자동차', es: 'Coche', fr: 'Voiture'},
  '車・電車||Car / train': {zh: '汽车・电车', ko: '자동차·전철', es: 'Coche / tren', fr: 'Voiture / train'},
  '変更||Change': {zh: '更改', ko: '변경', es: 'Cambiar', fr: 'Modifier'},
  'パスワードを変更||Change password': {zh: '更改密码', ko: '비밀번호 변경', es: 'Cambiar contraseña', fr: 'Changer le mot de passe'},
  '移動手段を変更||Change transport': {zh: '更改交通方式', ko: '이동 수단 변경', es: 'Cambiar el transporte', fr: 'Changer de transport'},
  'たくさん||Chatty': {zh: '很多', ko: '많이', es: 'Mucho', fr: 'Très bavard'},
  '中国||China': {zh: '中国', ko: '중국', es: 'China', fr: 'Chine'},
  '旅行を選択||Choose a trip': {zh: '选择旅行', ko: '여행 선택', es: 'Elegir un viaje', fr: 'Choisir un voyage'},
  '次の話を選んでいます…||Choosing the next story…': {zh: '正在选下一个故事…', ko: '다음 이야기를 고르는 중…', es: 'Eligiendo la siguiente historia…', fr: 'Choix de l’histoire suivante…'},
  'メールのコード||Code from the email': {zh: '邮件中的验证码', ko: '메일의 코드', es: 'Código del correo', fr: 'Code de l’e-mail'},
  '通勤・通学||Commute': {zh: '通勤通学', ko: '통근·통학', es: 'Trayecto diario', fr: 'Trajet quotidien'},
  '同行者||Companions': {zh: '同行者', ko: '동행', es: 'Acompañantes', fr: 'Compagnons'},
  '信頼度||Confidence': {zh: '可信度', ko: '신뢰도', es: 'Confianza', fr: 'Confiance'},
  '本人確認の方法||Confirm it is you': {zh: '确认是本人', ko: '본인 확인 방법', es: 'Confirme que es usted', fr: 'Confirmez que c’est vous'},
  '続ける||Continue': {zh: '继续', ko: '계속', es: 'Continuar', fr: 'Continuer'},
  '本人確認に失敗しました。||Could not confirm your identity.': {zh: '未能确认身份。', ko: '본인 확인에 실패했습니다.', es: 'No se pudo confirmar su identidad.', fr: 'Impossible de confirmer votre identité.'},
  '住んでいる国||Country you live in': {zh: '居住的国家', ko: '사는 나라', es: 'País donde vive', fr: 'Pays où vous vivez'},
  '新規登録||Create account': {zh: '注册', ko: '회원가입', es: 'Crear cuenta', fr: 'Créer un compte'},
  '登録する||Create account': {zh: '注册', ko: '가입하기', es: 'Registrarse', fr: 'S’inscrire'},
  'IDとパスワードで新規登録||Create an account with ID and password': {zh: '用 ID 和密码注册', ko: 'ID와 비밀번호로 가입', es: 'Crear una cuenta con ID y contraseña', fr: 'Créer un compte avec identifiant et mot de passe'},
  '文化||Culture': {zh: '文化', ko: '문화', es: 'Cultura', fr: 'Culture'},
  '自転車程度||Cycling speed': {zh: '自行车速度', ko: '자전거 속도', es: 'Velocidad de bicicleta', fr: 'Vitesse de vélo'},
  'チェコ||Czechia': {zh: '捷克', ko: '체코', es: 'Chequia', fr: 'Tchéquie'},
  '削除する||Delete': {zh: '删除', ko: '삭제', es: 'Eliminar', fr: 'Supprimer'},
  'アカウントを削除||Delete account': {zh: '删除账号', ko: '계정 삭제', es: 'Eliminar cuenta', fr: 'Supprimer le compte'},
  'アカウントを削除しますか？||Delete your account?': {zh: '要删除账号吗？', ko: '계정을 삭제할까요?', es: '¿Eliminar su cuenta?', fr: 'Supprimer votre compte ?'},
  '削除しました||Deleted': {zh: '已删除', ko: '삭제했습니다', es: 'Eliminada', fr: 'Supprimé'},
  '削除しました。Appleとの連携解除は自動で再試行します。||Deleted. Apple disconnection will be retried automatically.': {zh: '已删除。与 Apple 的解除关联会自动重试。', ko: '삭제했습니다. Apple 연동 해제는 자동으로 다시 시도합니다.', es: 'Eliminada. La desconexión de Apple se reintentará sola.', fr: 'Supprimé. La déconnexion d’Apple sera relancée automatiquement.'},
  'デンマーク||Denmark': {zh: '丹麦', ko: '덴마크', es: 'Dinamarca', fr: 'Danemark'},
  '説明の長さ||Detail': {zh: '讲解长度', ko: '설명 길이', es: 'Nivel de detalle', fr: 'Niveau de détail'},
  '詳しく||Detailed': {zh: '详细', ko: '자세히', es: 'Detallado', fr: 'Détaillé'},
  '移動を判定中||Detecting movement': {zh: '正在判断移动', ko: '이동 판별 중', es: 'Detectando el movimiento', fr: 'Détection du mouvement'},
  '端末の位置情報がオフです。||Device location is turned off.': {zh: '设备的定位已关闭。', ko: '기기의 위치 정보가 꺼져 있습니다.', es: 'La ubicación del dispositivo está desactivada.', fr: 'La localisation de l’appareil est désactivée.'},
  '表示名||Display name': {zh: '显示名', ko: '표시 이름', es: 'Nombre visible', fr: 'Nom affiché'},
  '表示名（任意）||Display name (optional)': {zh: '显示名（可选）', ko: '표시 이름(선택)', es: 'Nombre visible (opcional)', fr: 'Nom affiché (facultatif)'},
  '例: しばらく建築を多めに||e.g. more architecture for a while': {zh: '例如：先多讲一些建筑', ko: '예: 잠시 건축을 더', es: 'p. ej., más arquitectura un rato', fr: 'p. ex. plus d’architecture un moment'},
  '選んだ言語で、上から順に続けて話します。ドラッグで順番を変えられます。||Each story is told in every language below, top to bottom. Drag to reorder.': {zh: '每个故事会按从上到下的顺序，用所选语言依次讲述。拖动可调整顺序。', ko: '고른 언어로 위에서부터 차례로 이야기합니다. 끌어 순서를 바꿀 수 있습니다.', es: 'Cada historia se cuenta en los idiomas de abajo, de arriba abajo. Arrastre para reordenar.', fr: 'Chaque histoire est dite dans les langues ci-dessous, de haut en bas. Glissez pour réordonner.'},
  'エジプト||Egypt': {zh: '埃及', ko: '이집트', es: 'Egipto', fr: 'Égypte'},
  'この話題はもう十分||Enough of this topic': {zh: '这个话题够了', ko: '이 주제는 충분해요', es: 'Basta de este tema', fr: 'Assez de ce sujet'},
  'メール確認コードを入力||Enter email verification code': {zh: '输入邮件验证码', ko: '메일 확인 코드 입력', es: 'Introducir el código del correo', fr: 'Saisir le code de l’e-mail'},
  'パスワードを入力||Enter your password': {zh: '输入密码', ko: '비밀번호 입력', es: 'Introduzca su contraseña', fr: 'Saisissez votre mot de passe'},
  '暮らし||Everyday life': {zh: '日常生活', ko: '일상', es: 'Vida cotidiana', fr: 'Vie quotidienne'},
  '終了||Finish': {zh: '结束', ko: '종료', es: 'Terminar', fr: 'Terminer'},
  'ガイドを終了しますか？||Finish the guide?': {zh: '结束导览吗？', ko: '가이드를 종료할까요?', es: '¿Terminar la guía?', fr: 'Terminer le guide ?'},
  '終了しています…||Finishing…': {zh: '正在结束…', ko: '종료하는 중…', es: 'Terminando…', fr: 'Fermeture…'},
  'フィンランド||Finland': {zh: '芬兰', ko: '핀란드', es: 'Finlandia', fr: 'Finlande'},
  '食||Food': {zh: '美食', ko: '음식', es: 'Comida', fr: 'Cuisine'},
  'パスワードを忘れた場合||Forgot password?': {zh: '忘记密码？', ko: '비밀번호를 잊으셨나요?', es: '¿Olvidó la contraseña?', fr: 'Mot de passe oublié ?'},
  'フランス||France': {zh: '法国', ko: '프랑스', es: 'Francia', fr: 'France'},
  'ドイツ||Germany': {zh: '德国', ko: '독일', es: 'Alemania', fr: 'Allemagne'},
  'ギリシャ||Greece': {zh: '希腊', ko: '그리스', es: 'Grecia', fr: 'Grèce'},
  'ガイド中||Guiding': {zh: '导览中', ko: '가이드 중', es: 'Guiando', fr: 'Guide en cours'},
  'ガイドを再開します||Guiding resumed': {zh: '导览已恢复', ko: '가이드를 다시 시작합니다', es: 'La guía se reanuda', fr: 'Le guide reprend'},
  'パスワードを隠す||Hide password': {zh: '隐藏密码', ko: '비밀번호 숨기기', es: 'Ocultar contraseña', fr: 'Masquer le mot de passe'},
  '多め||High': {zh: '多', ko: '많음', es: 'Alto', fr: 'Élevé'},
  '高速移動||High speed': {zh: '高速移动', ko: '고속 이동', es: 'Alta velocidad', fr: 'Grande vitesse'},
  '歴史||History': {zh: '历史', ko: '역사', es: 'Historia', fr: 'Histoire'},
  '香港||Hong Kong': {zh: '香港', ko: '홍콩', es: 'Hong Kong', fr: 'Hong Kong'},
  '話しかける頻度||How often to talk': {zh: '讲述频率', ko: '이야기 빈도', es: 'Frecuencia', fr: 'Fréquence'},
  'この話はどうでしたか？||How was this story?': {zh: '这个故事怎么样？', ko: '이 이야기는 어땠나요?', es: '¿Qué le pareció esta historia?', fr: 'Que pensez-vous de cette histoire ?'},
  'ID・パスワード（未設定）||ID & password (not set)': {zh: 'ID 和密码（未设置）', ko: 'ID·비밀번호(미설정)', es: 'ID y contraseña (sin definir)', fr: 'Identifiant et mot de passe (non définis)'},
  '登録があればメールを送りました。||If the account exists, an email was sent.': {zh: '如果账号存在，我们已发送邮件。', ko: '계정이 있으면 메일을 보냈습니다.', es: 'Si la cuenta existe, se envió un correo.', fr: 'Si le compte existe, un e-mail a été envoyé.'},
  '確認済みの回復用メールがある場合、再設定コードを送ります。||If you have a verified recovery email, we will send a reset code.': {zh: '如果已有确认过的恢复邮箱，我们会发送重置码。', ko: '확인된 복구 메일이 있으면 재설정 코드를 보냅니다.', es: 'Si tiene un correo de recuperación verificado, enviaremos un código.', fr: 'S’il existe un e-mail de récupération vérifié, un code sera envoyé.'},
  'ガイド中||In progress': {zh: '进行中', ko: '진행 중', es: 'En curso', fr: 'En cours'},
  'インド||India': {zh: '印度', ko: '인도', es: 'India', fr: 'Inde'},
  'インドネシア||Indonesia': {zh: '印度尼西亚', ko: '인도네시아', es: 'Indonesia', fr: 'Indonésie'},
  '産業||Industry': {zh: '产业', ko: '산업', es: 'Industria', fr: 'Industrie'},
  '面白い||Interesting': {zh: '有趣', ko: '재미있어요', es: 'Interesante', fr: 'Intéressant'},
  '興味||Interests': {zh: '兴趣', ko: '관심사', es: 'Intereses', fr: 'Centres d’intérêt'},
  'アイルランド||Ireland': {zh: '爱尔兰', ko: '아일랜드', es: 'Irlanda', fr: 'Irlande'},
  'イタリア||Italy': {zh: '意大利', ko: '이탈리아', es: 'Italia', fr: 'Italie'},
  '日本||Japan': {zh: '日本', ko: '일본', es: 'Japón', fr: 'Japon'},
  '知ってた||Knew it': {zh: '已经知道', ko: '알고 있었어요', es: 'Ya lo sabía', fr: 'Je le savais'},
  '好き||Like': {zh: '喜欢', ko: '좋아함', es: 'Me gusta', fr: 'J’aime'},
  '連携||Link': {zh: '关联', ko: '연동', es: 'Vincular', fr: 'Associer'},
  '連携済み||Linked': {zh: '已关联', ko: '연동됨', es: 'Vinculado', fr: 'Associé'},
  '詳しい内容を読み込んでいます…||Loading more detail…': {zh: '正在加载更多内容…', ko: '자세한 내용을 불러오는 중…', es: 'Cargando más detalle…', fr: 'Chargement du détail…'},
  'ガイド中だけ位置情報を使います。終了するといつでも止まります。||Location is used only while guiding and stops when you finish.': {zh: '只在导览期间使用位置。结束后随时停止。', ko: '가이드 중에만 위치를 사용하며, 종료하면 바로 멈춥니다.', es: 'La ubicación se usa solo durante la guía y se detiene al terminar.', fr: 'La position n’est utilisée que pendant le guide et s’arrête à la fin.'},
  '位置情報が許可されていません。設定で許可してください。||Location permission is off. Allow it in Settings.': {zh: '未允许定位。请在设置中开启。', ko: '위치 권한이 없습니다. 설정에서 허용해 주세요.', es: 'El permiso de ubicación está desactivado. Actívelo en Ajustes.', fr: 'La localisation n’est pas autorisée. Activez-la dans Réglages.'},
  '位置情報の取得と音声を止めます。||Location tracking and audio will stop.': {zh: '将停止定位和语音。', ko: '위치 수집과 음성을 멈춥니다.', es: 'Se detendrán la ubicación y el audio.', fr: 'La localisation et l’audio s’arrêteront.'},
  'ログインID||Login ID': {zh: '登录 ID', ko: '로그인 ID', es: 'ID de acceso', fr: 'Identifiant'},
  '大好き||Love': {zh: '非常喜欢', ko: '아주 좋아함', es: 'Me encanta', fr: 'J’adore'},
  '少なめ||Low': {zh: '少', ko: '적음', es: 'Bajo', fr: 'Faible'},
  'マレーシア||Malaysia': {zh: '马来西亚', ko: '말레이시아', es: 'Malasia', fr: 'Malaisie'},
  '地図||Map': {zh: '地图', ko: '지도', es: 'Mapa', fr: 'Carte'},
  'メキシコ||Mexico': {zh: '墨西哥', ko: '멕시코', es: 'México', fr: 'Mexique'},
  '詳しく||More': {zh: '详细', ko: '자세히', es: 'Más', fr: 'Plus'},
  '関連する話を||More like this': {zh: '更多相关的', ko: '비슷한 이야기', es: 'Más parecidas', fr: 'Dans le même esprit'},
  '関連する話を増やします||More related stories': {zh: '会多讲相关的故事', ko: '관련 이야기를 더합니다', es: 'Habrá más historias relacionadas', fr: 'Plus d’histoires liées'},
  '名前||Name': {zh: '名字', ko: '이름', es: 'Nombre', fr: 'Nom'},
  '解説の言語||Narration languages': {zh: '讲解语言', ko: '해설 언어', es: 'Idiomas de la narración', fr: 'Langues de la narration'},
  '自然||Nature': {zh: '自然', ko: '자연', es: 'Naturaleza', fr: 'Nature'},
  'オランダ||Netherlands': {zh: '荷兰', ko: '네덜란드', es: 'Países Bajos', fr: 'Pays-Bas'},
  '新しいパスワード||New password': {zh: '新密码', ko: '새 비밀번호', es: 'Nueva contraseña', fr: 'Nouveau mot de passe'},
  '新しいパスワード（15文字以上）||New password (15+ chars)': {zh: '新密码（15个字符以上）', ko: '새 비밀번호(15자 이상)', es: 'Nueva contraseña (15+ caracteres)', fr: 'Nouveau mot de passe (15 caractères ou plus)'},
  'ニュージーランド||New Zealand': {zh: '新西兰', ko: '뉴질랜드', es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande'},
  '次の話||Next': {zh: '下一个', ko: '다음', es: 'Siguiente', fr: 'Suivante'},
  'この旅行ではまだガイドがありません||No guides in this trip': {zh: '这次旅行还没有讲解', ko: '이 여행에는 아직 가이드가 없습니다', es: 'Aún no hay guías en este viaje', fr: 'Pas encore de guide pour ce voyage'},
  '近くの話はもうありません。周りの話を準備しています||No more stories nearby. Preparing stories around you': {zh: '附近没有更多故事了。正在准备周围的故事', ko: '근처 이야기가 더 없습니다. 주변 이야기를 준비합니다', es: 'No quedan historias cerca. Preparando las de alrededor', fr: 'Plus d’histoires à proximité. Préparation de celles d’alentour'},
  '表示できる移動記録がありません||No track to show': {zh: '没有可显示的移动记录', ko: '표시할 이동 기록이 없습니다', es: 'No hay recorrido que mostrar', fr: 'Aucun tracé à afficher'},
  'まだ旅行がありません||No trips yet': {zh: '还没有旅行', ko: '아직 여행이 없습니다', es: 'Aún no hay viajes', fr: 'Pas encore de voyage'},
  '興味なし||None': {zh: '不感兴趣', ko: '관심 없음', es: 'Ninguno', fr: 'Aucun'},
  'ふつう||Normal': {zh: '普通', ko: '보통', es: 'Normal', fr: 'Normal'},
  'ノルウェー||Norway': {zh: '挪威', ko: '노르웨이', es: 'Noruega', fr: 'Norvège'},
  '興味なし||Not for me': {zh: '不感兴趣', ko: '관심 없음', es: 'No es para mí', fr: 'Pas pour moi'},
  '未連携||Not linked': {zh: '未关联', ko: '연동 안 됨', es: 'No vinculado', fr: 'Non associé'},
  '未設定||Not set': {zh: '未设置', ko: '미설정', es: 'Sin definir', fr: 'Non défini'},
  'うまく理解できませんでした。例:「しばらく建築を多めに」「30分静かに」||Not understood. Try "more architecture for a while" or "quiet for 30 min".': {zh: '没能理解。例如：「先多讲一些建筑」「安静30分钟」', ko: '이해하지 못했습니다. 예: 「잠시 건축을 더」「30분 조용히」', es: 'No se entendió. Pruebe «más arquitectura un rato» o «silencio 30 min».', fr: 'Pas compris. Essayez « plus d’architecture un moment » ou « silence pendant 30 min ».'},
  'イヤホン利用時などに。初期設定はオフです。||Off by default. Useful with earphones.': {zh: '默认关闭。戴耳机时很合适。', ko: '기본값은 꺼짐. 이어폰을 쓸 때 편리합니다.', es: 'Desactivado por defecto. Útil con auriculares.', fr: 'Désactivé par défaut. Pratique avec des écouteurs.'},
  'オフライン：位置は端末に保存し、通信回復後に送ります||Offline: points are saved and sent later': {zh: '离线：位置会保存在设备上，恢复网络后再发送', ko: '오프라인: 위치는 기기에 저장했다가 통신이 돌아오면 보냅니다', es: 'Sin conexión: los puntos se guardan y se envían después', fr: 'Hors ligne : les points sont enregistrés et envoyés plus tard'},
  '左手||on the left': {zh: '左侧', ko: '왼쪽', es: 'a la izquierda', fr: 'à gauche'},
  '右手||on the right': {zh: '右侧', ko: '오른쪽', es: 'a la derecha', fr: 'à droite'},
  '地図を開く||Open map': {zh: '打开地图', ko: '지도 열기', es: 'Abrir el mapa', fr: 'Ouvrir la carte'},
  'その他||Other': {zh: '其他', ko: '기타', es: 'Otro', fr: 'Autre'},
  '変更すると他の端末はログアウトされます。||Other devices will be signed out.': {zh: '更改后其他设备会退出登录。', ko: '변경하면 다른 기기는 로그아웃됩니다.', es: 'Los demás dispositivos cerrarán la sesión.', fr: 'Les autres appareils seront déconnectés.'},
  'パスワード||Password': {zh: '密码', ko: '비밀번호', es: 'Contraseña', fr: 'Mot de passe'},
  '再設定しました。新しいパスワードでログインしてください。||Password reset. Please sign in.': {zh: '已重置。请用新密码登录。', ko: '재설정했습니다. 새 비밀번호로 로그인해 주세요.', es: 'Contraseña restablecida. Inicie sesión.', fr: 'Mot de passe réinitialisé. Connectez-vous.'},
  'パスワードが弱すぎます（15文字以上、よくある語句は不可）。||Password too weak (15+ chars, not a common phrase).': {zh: '密码太弱（至少15个字符，不能是常见短语）。', ko: '비밀번호가 너무 약합니다(15자 이상, 흔한 문구는 불가).', es: 'Contraseña demasiado débil (15+ caracteres, sin frases comunes).', fr: 'Mot de passe trop faible (15 caractères ou plus, pas une phrase courante).'},
  'これまでの旅行||Past trips': {zh: '以往的旅行', ko: '지금까지의 여행', es: 'Viajes anteriores', fr: 'Voyages passés'},
  'フィリピン||Philippines': {zh: '菲律宾', ko: '필리핀', es: 'Filipinas', fr: 'Philippines'},
  '読み上げ||Play': {zh: '朗读', ko: '읽어 주기', es: 'Reproducir', fr: 'Lire'},
  'もう一度本人確認してください。||Please confirm it is you again.': {zh: '请再次确认是本人。', ko: '다시 본인 확인해 주세요.', es: 'Vuelva a confirmar que es usted.', fr: 'Confirmez à nouveau que c’est vous.'},
  'ポーランド||Poland': {zh: '波兰', ko: '폴란드', es: 'Polonia', fr: 'Pologne'},
  'ポルトガル||Portugal': {zh: '葡萄牙', ko: '포르투갈', es: 'Portugal', fr: 'Portugal'},
  '実用||Practical': {zh: '实用', ko: '실용', es: 'Práctico', fr: 'Pratique'},
  '目的||Purpose': {zh: '目的', ko: '목적', es: 'Propósito', fr: 'Motif'},
  '控えめ||Quiet': {zh: '少讲', ko: '조용히', es: 'Poco', fr: 'Discret'},
  '30分静かに||Quiet for 30 min': {zh: '安静30分钟', ko: '30분 조용히', es: 'Silencio durante 30 min', fr: 'Silence pendant 30 min'},
  '新しい話を自動で読み上げる||Read new stories aloud automatically': {zh: '自动朗读新故事', ko: '새 이야기를 자동으로 읽어 주기', es: 'Leer las historias nuevas en voz alta', fr: 'Lire les nouvelles histoires à voix haute'},
  '現在地へ||Recenter': {zh: '回到当前位置', ko: '현재 위치로', es: 'Volver a mi posición', fr: 'Revenir à ma position'},
  '回復用メール||Recovery email': {zh: '恢复邮箱', ko: '복구 메일', es: 'Correo de recuperación', fr: 'E-mail de récupération'},
  '回復用メール（任意）||Recovery email (optional)': {zh: '恢复邮箱（可选）', ko: '복구 메일(선택)', es: 'Correo de recuperación (opcional)', fr: 'E-mail de récupération (facultatif)'},
  '外す||Remove': {zh: '移除', ko: '빼기', es: 'Quitar', fr: 'Retirer'},
  '同行者を外す||Remove companion': {zh: '移除同行者', ko: '동행 빼기', es: 'Quitar acompañante', fr: 'Retirer le compagnon'},
  '報告しました。確認まで表示を止めます。||Reported; hidden until reviewed.': {zh: '已报告。审核前不再显示。', ko: '신고했습니다. 확인할 때까지 표시하지 않습니다.', es: 'Enviado; oculto hasta la revisión.', fr: 'Signalé ; masqué jusqu’à vérification.'},
  '再設定する||Reset': {zh: '重置', ko: '재설정', es: 'Restablecer', fr: 'Réinitialiser'},
  'パスワード再設定||Reset password': {zh: '重置密码', ko: '비밀번호 재설정', es: 'Restablecer contraseña', fr: 'Réinitialiser le mot de passe'},
  '地図で振り返る||Review on the map': {zh: '在地图上回顾', ko: '지도로 돌아보기', es: 'Revisar en el mapa', fr: 'Revoir sur la carte'},
  '試聴||Sample': {zh: '试听', ko: '미리 듣기', es: 'Muestra', fr: 'Écouter'},
  '試聴できませんでした||Sample unavailable': {zh: '无法试听', ko: '미리 듣기를 할 수 없습니다', es: 'Muestra no disponible', fr: 'Écoute impossible'},
  '保存しました||Saved': {zh: '已保存', ko: '저장했습니다', es: 'Guardado', fr: 'Enregistré'},
  '反映しています…||Saving…': {zh: '正在保存…', ko: '반영하는 중…', es: 'Guardando…', fr: 'Enregistrement…'},
  '言語を検索||Search languages': {zh: '搜索语言', ko: '언어 검색', es: 'Buscar idiomas', fr: 'Chercher une langue'},
  '季節||Seasonal': {zh: '时令', ko: '계절', es: 'Temporada', fr: 'Saison'},
  '送信||Send': {zh: '发送', ko: '보내기', es: 'Enviar', fr: 'Envoyer'},
  'コードを送る||Send code': {zh: '发送验证码', ko: '코드 보내기', es: 'Enviar código', fr: 'Envoyer le code'},
  'サーバー音声は現在使えません。端末の読み上げを許可すると代わりに使います。||Server voices are unavailable now. Allow device speech to use it instead.': {zh: '服务器语音目前不可用。允许设备朗读后会改用它。', ko: '서버 음성을 지금은 쓸 수 없습니다. 기기 읽기를 허용하면 대신 사용합니다.', es: 'Las voces del servidor no están disponibles. Permita la voz del dispositivo.', fr: 'Les voix du serveur sont indisponibles. Autorisez la voix de l’appareil.'},
  '設定||Settings': {zh: '设置', ko: '설정', es: 'Ajustes', fr: 'Réglages'},
  '新幹線||Shinkansen': {zh: '新干线', ko: '신칸센', es: 'Shinkansen', fr: 'Shinkansen'},
  '船||Ship': {zh: '船', ko: '배', es: 'Barco', fr: 'Bateau'},
  '短く||Short': {zh: '简短', ko: '짧게', es: 'Breve', fr: 'Court'},
  'パスワードを表示||Show password': {zh: '显示密码', ko: '비밀번호 표시', es: 'Mostrar contraseña', fr: 'Afficher le mot de passe'},
  '全体を表示||Show whole track': {zh: '显示全部路线', ko: '전체 보기', es: 'Ver todo el recorrido', fr: 'Afficher tout le tracé'},
  'ログイン||Sign in': {zh: '登录', ko: '로그인', es: 'Iniciar sesión', fr: 'Se connecter'},
  'Appleでサインイン||Sign in with Apple': {zh: '通过 Apple 登录', ko: 'Apple로 로그인', es: 'Iniciar sesión con Apple', fr: 'Se connecter avec Apple'},
  'Googleでログイン||Sign in with Google': {zh: '通过 Google 登录', ko: 'Google로 로그인', es: 'Iniciar sesión con Google', fr: 'Se connecter avec Google'},
  'ログアウト||Sign out': {zh: '退出登录', ko: '로그아웃', es: 'Cerrar sesión', fr: 'Se déconnecter'},
  'ログイン方法||Sign-in methods': {zh: '登录方式', ko: '로그인 방법', es: 'Métodos de acceso', fr: 'Méthodes de connexion'},
  'シンガポール||Singapore': {zh: '新加坡', ko: '싱가포르', es: 'Singapur', fr: 'Singapour'},
  '出典・信頼度||Sources & confidence': {zh: '出处与可信度', ko: '출처·신뢰도', es: 'Fuentes y confianza', fr: 'Sources et confiance'},
  '南アフリカ||South Africa': {zh: '南非', ko: '남아프리카', es: 'Sudáfrica', fr: 'Afrique du Sud'},
  '韓国||South Korea': {zh: '韩国', ko: '한국', es: 'Corea del Sur', fr: 'Corée du Sud'},
  'スペイン||Spain': {zh: '西班牙', ko: '스페인', es: 'España', fr: 'Espagne'},
  '速さ||Speed': {zh: '语速', ko: '속도', es: 'Velocidad', fr: 'Vitesse'},
  'ガイドを開始||Start guide': {zh: '开始导览', ko: '가이드 시작', es: 'Empezar la guía', fr: 'Commencer le guide'},
  '停止||Stop': {zh: '停止', ko: '정지', es: 'Detener', fr: 'Arrêter'},
  '停止中||Stopped': {zh: '已停下', ko: '정지 중', es: 'Parado', fr: 'À l’arrêt'},
  '移動中に、その土地の話を。||Stories of the place you are passing.': {zh: '行进中，听听这片土地的故事。', ko: '이동하는 동안, 그 땅의 이야기를.', es: 'Historias del lugar por el que pasa.', fr: 'Les histoires du lieu que vous traversez.'},
  '要約||Summary': {zh: '摘要', ko: '요약', es: 'Resumen', fr: 'Résumé'},
  '意外な話題||Surprise topics': {zh: '意外的话题', ko: '뜻밖의 이야기', es: 'Temas inesperados', fr: 'Sujets inattendus'},
  'スウェーデン||Sweden': {zh: '瑞典', ko: '스웨덴', es: 'Suecia', fr: 'Suède'},
  'スイス||Switzerland': {zh: '瑞士', ko: '스위스', es: 'Suiza', fr: 'Suisse'},
  '台湾||Taiwan': {zh: '台湾', ko: '대만', es: 'Taiwán', fr: 'Taïwan'},
  '多め||Talkative': {zh: '较多', ko: '자주', es: 'A menudo', fr: 'Bavard'},
  'タイ||Thailand': {zh: '泰国', ko: '태국', es: 'Tailandia', fr: 'Thaïlande'},
  'このアカウントは別のLocalVoiceユーザーに連携済みです。||That account is linked to another LocalVoice user.': {zh: '该账号已关联到其他 LocalVoice 用户。', ko: '이 계정은 다른 LocalVoice 사용자와 연동되어 있습니다.', es: 'Esa cuenta está vinculada a otro usuario de LocalVoice.', fr: 'Ce compte est associé à un autre utilisateur LocalVoice.'},
  'ログイン先のサービスに接続できません。||The sign-in provider is unavailable.': {zh: '无法连接登录服务。', ko: '로그인 서비스에 연결할 수 없습니다.', es: 'El servicio de acceso no está disponible.', fr: 'Le service de connexion est indisponible.'},
  '同行者の興味も話題選びに反映します。この旅行の中だけで使います。||Their interests are used for this trip only.': {zh: '同行者的兴趣也会影响选题。仅在这次旅行中使用。', ko: '동행의 관심사도 이야기 선택에 반영합니다. 이 여행에서만 씁니다.', es: 'Sus intereses cuentan solo en este viaje.', fr: 'Leurs intérêts ne comptent que pour ce voyage.'},
  'このIDは使われています。||This ID is already taken.': {zh: '这个 ID 已被使用。', ko: '이 ID는 이미 사용 중입니다.', es: 'Este ID ya está en uso.', fr: 'Cet identifiant est déjà pris.'},
  'しばらくこの話題を控えます||This topic will pause for a while': {zh: '这个话题会先少讲一会儿', ko: '이 주제는 잠시 줄입니다', es: 'Este tema se pausará un rato', fr: 'Ce sujet sera mis en pause un moment'},
  '試行回数が多すぎます。しばらく待ってください。||Too many attempts. Please wait a while.': {zh: '尝试次数过多。请稍后再试。', ko: '시도 횟수가 너무 많습니다. 잠시 기다려 주세요.', es: 'Demasiados intentos. Espere un momento.', fr: 'Trop de tentatives. Patientez un moment.'},
  '電車||Train': {zh: '电车', ko: '전철', es: 'Tren', fr: 'Train'},
  '移動手段||Transport': {zh: '交通方式', ko: '이동 수단', es: 'Transporte', fr: 'Transport'},
  '旅行||Travel': {zh: '旅行', ko: '여행', es: 'Viaje', fr: 'Voyage'},
  '旅行の記録||Trip record': {zh: '旅行记录', ko: '여행 기록', es: 'Registro del viaje', fr: 'Journal du voyage'},
  'トルコ||Türkiye': {zh: '土耳其', ko: '튀르키예', es: 'Turquía', fr: 'Türkiye'},
  'アラブ首長国連邦||United Arab Emirates': {zh: '阿拉伯联合酋长国', ko: '아랍에미리트', es: 'Emiratos Árabes Unidos', fr: 'Émirats arabes unis'},
  'イギリス||United Kingdom': {zh: '英国', ko: '영국', es: 'Reino Unido', fr: 'Royaume-Uni'},
  'アメリカ||United States': {zh: '美国', ko: '미국', es: 'Estados Unidos', fr: 'États-Unis'},
  '解除||Unlink': {zh: '解除关联', ko: '연동 해제', es: 'Desvincular', fr: 'Dissocier'},
  'サーバー音声が使えないとき端末で読み上げる||Use device speech when server audio is unavailable': {zh: '服务器语音不可用时，用设备朗读', ko: '서버 음성을 쓸 수 없을 때 기기에서 읽어 주기', es: 'Usar la voz del dispositivo si falla el audio del servidor', fr: 'Utiliser la voix de l’appareil si l’audio du serveur manque'},
  'パスワードを忘れたときの再設定に使います||Used to reset a forgotten password': {zh: '用于忘记密码时重置', ko: '비밀번호를 잊었을 때 재설정하는 데 씁니다', es: 'Se usa para restablecer una contraseña olvidada', fr: 'Sert à réinitialiser un mot de passe oublié'},
  '確認メールを送りました||Verification email sent': {zh: '已发送确认邮件', ko: '확인 메일을 보냈습니다', es: 'Correo de verificación enviado', fr: 'E-mail de vérification envoyé'},
  '確認しました。||Verified.': {zh: '已确认。', ko: '확인했습니다.', es: 'Verificado.', fr: 'Vérifié.'},
  '確認する||Verify': {zh: '确认', ko: '확인', es: 'Verificar', fr: 'Vérifier'},
  'メール確認||Verify email': {zh: '确认邮箱', ko: '메일 확인', es: 'Verificar correo', fr: 'Vérifier l’e-mail'},
  'ベトナム||Vietnam': {zh: '越南', ko: '베트남', es: 'Vietnam', fr: 'Viêt Nam'},
  '地図で見る||View on map': {zh: '在地图上查看', ko: '지도로 보기', es: 'Ver en el mapa', fr: 'Voir sur la carte'},
  '音声||Voice': {zh: '语音', ko: '음성', es: 'Voz', fr: 'Voix'},
  '位置情報を待っています…||Waiting for location…': {zh: '正在等待位置…', ko: '위치를 기다리는 중…', es: 'Esperando la ubicación…', fr: 'Attente de la position…'},
  '徒歩||Walk': {zh: '步行', ko: '도보', es: 'A pie', fr: 'À pied'},
  '散歩||Walk': {zh: '散步', ko: '산책', es: 'Paseo', fr: 'Promenade'},
  '徒歩||Walking': {zh: '步行', ko: '도보', es: 'Caminando', fr: 'À pied'},
  '近くに話題があればお知らせします。画面を閉じてもガイドは続きます。||We will tell you when there is a story nearby. Guiding continues with the screen off.': {zh: '附近有故事时会告诉你。关掉屏幕导览也会继续。', ko: '근처에 이야기가 있으면 알려 드립니다. 화면을 닫아도 가이드는 이어집니다.', es: 'Avisaremos cuando haya una historia cerca. La guía sigue con la pantalla apagada.', fr: 'Nous vous le dirons s’il y a une histoire à proximité. Le guide continue écran éteint.'},
  'IDまたはパスワードが違います。||Wrong ID or password.': {zh: 'ID 或密码不正确。', ko: 'ID 또는 비밀번호가 다릅니다.', es: 'ID o contraseña incorrectos.', fr: 'Identifiant ou mot de passe incorrect.'},
  '情報が違う||Wrong info': {zh: '信息不对', ko: '정보가 다름', es: 'Información incorrecta', fr: 'Info incorrecte'},
  '最後のログイン方法は解除できません。||You cannot remove your last sign-in method.': {zh: '不能解除最后一种登录方式。', ko: '마지막 로그인 방법은 해제할 수 없습니다.', es: 'No puede quitar su último método de acceso.', fr: 'Vous ne pouvez pas retirer votre dernière méthode de connexion.'},
  '通信が戻るまで移動を端末に記録します。||Your movement is saved on this device until the connection returns.': {zh: '在网络恢复前，移动会记录在这台设备上。', ko: '통신이 돌아올 때까지 이동을 이 기기에 기록합니다.', es: 'El movimiento se guarda en el dispositivo hasta que vuelva la conexión.', fr: 'Le déplacement est enregistré sur l’appareil jusqu’au retour du réseau.'},
  '日本語||Japanese': {zh: '日语', ko: '일본어', es: 'Japonés', fr: 'Japonais'},
  '英語||English': {zh: '英语', ko: '영어', es: 'Inglés', fr: 'Anglais'},
  '中国語||Chinese': {zh: '中文', ko: '중국어', es: 'Chino', fr: 'Chinois'},
  '韓国語||Korean': {zh: '韩语', ko: '한국어', es: 'Coreano', fr: 'Coréen'},
  'スペイン語||Spanish': {zh: '西班牙语', ko: '스페인어', es: 'Español', fr: 'Espagnol'},
  'フランス語||French': {zh: '法语', ko: '프랑스어', es: 'Francés', fr: 'Français'},
};
